### PR TITLE
Vector layer download

### PR DESCRIPTION
**Pull request by RoProducts**
Implementation for https://github.com/geosolutions-it/GeoCollect/issues/3

### CODE REVIEW

**Comment by Gnafu** [comment]
Please add a feedback to the user during the vector download and database update.
Take into consideration that the update process can take some time and the user may interact with the application in the meanwhile.

**Comment by RoProducts** [comment]
I added a dialog asking the user to download the vector data. It it is downloaded or the user denies it the raster background data is checked/downloaded.

**Comment by Gnafu** [comment]
Can you please resolve the conflicts?

**Comment by RoProducts** [comment]
Fixed

**Comment by Gnafu** [comment]
I was able to download a vector layer but the map did not show it.
I extracted the spatialite database and it was visible in QGIS.

Then after selecting the same mission in the left menu I got this crash:

```
11-08 15:25:21.806: E/AndroidRuntime(16241): FATAL EXCEPTION: main
11-08 15:25:21.806: E/AndroidRuntime(16241): Process: it.geosolutions.geocollect.android.app, PID: 16241
11-08 15:25:21.806: E/AndroidRuntime(16241): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=7001, result=-1, data=Intent { (has extras) }} to activity {it.geosolutions.geocollect.android.app/it.geosolutions.geocollect.android.core.mission.PendingMissionListActivity}: java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2
11-08 15:25:21.806: E/AndroidRuntime(16241): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3566)
11-08 15:25:21.806: E/AndroidRuntime(16241): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3609)
11-08 15:25:21.806: E/AndroidRuntime(16241): 	at android.app.ActivityThread.access$1300(ActivityThread.java:147)
11-08 15:25:21.806: E/AndroidRuntime(16241): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1330)
11-08 15:25:21.806: E/AndroidRuntime(16241): 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-08 15:25:21.806: E/AndroidRuntime(16241): 	at android.os.Looper.loop(Looper.java:135)
11-08 15:25:21.806: E/AndroidRuntime(16241): 	at android.app.ActivityThread.main(ActivityThread.java:5264)
11-08 15:25:21.806: E/AndroidRuntime(16241): 	at java.lang.reflect.Method.invoke(Native Method)
11-08 15:25:21.806: E/AndroidRuntime(16241): 	at java.lang.reflect.Method.invoke(Method.java:372)
11-08 15:25:21.806: E/AndroidRuntime(16241): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
11-08 15:25:21.806: E/AndroidRuntime(16241): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
11-08 15:25:21.806: E/AndroidRuntime(16241): Caused by: java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2
11-08 15:25:21.806: E/AndroidRuntime(16241): 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
11-08 15:25:21.806: E/AndroidRuntime(16241): 	at java.util.ArrayList.get(ArrayList.java:308)
11-08 15:25:21.806: E/AndroidRuntime(16241): 	at it.geosolutions.geocollect.android.core.mission.PendingMissionListActivity.onNavItemSelected(PendingMissionListActivity.java:430)
11-08 15:25:21.806: E/AndroidRuntime(16241): 	at it.geosolutions.geocollect.android.core.mission.PendingMissionListActivity.onActivityResult(PendingMissionListActivity.java:621)
11-08 15:25:21.806: E/AndroidRuntime(16241): 	at android.app.Activity.dispatchActivityResult(Activity.java:6177)
11-08 15:25:21.806: E/AndroidRuntime(16241): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3562)
11-08 15:25:21.806: E/AndroidRuntime(16241): 	... 10 more
```

**Comment by Gnafu** [comment]
My bad, I misconfigured the mission.

**Pull request merged**
